ProjectInfo/Controllers/AchievementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectInfo.Context;
using ProjectInfo.Models;

namespace ProjectInfo.Controllers
{
    [Authorize]
    public class AchievementsController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        [AllowAnonymous]
        public ActionResult AchievementsOfProject(int? id)
        {
            var achievements = db.Achievements.Where(a => a.ProjectId == id);
            if (achievements == null) RedirectToAction("Index", "Home");
            achievements.ToList();
            var SortedAchievementsList = achievements.OrderByDescending(x => x.Update).ToList();
            return PartialView("_Achievements", SortedAchievementsList);
        }

        [AllowAnonymous]
        // GET: Achievements
        public ActionResult Index()
        {
            var achievements = db.Achievements.Include(a => a.SelectedProject);
            return View(achievements.ToList());
        }
        [AllowAnonymous]
        // GET: Achievements/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Achievement achievement = db.Achievements.Find(id);
            if (achievement == null)
            {
                return HttpNotFound();
            }
            return View(achievement);
        }

        // GET: Achievements/Create
        public ActionResult Create()
        {
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name");
            return View();
        }

        // POST: Achievements/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Update,ProjectId")] Achievement achievement)
        {
            if (ModelState.IsValid)
            {
                db.Achievements.Add(achievement);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", achievement.ProjectId);
            return View(achievement);
        }
        //-------------------------------------------------------
        
        public ActionResult CreateForProject()
        {
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name");
            return PartialView("_CreateForProject");
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateForProject([Bind(Include = "Id,Name,Update,ProjectId")] Achievement achievement)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Achievements.Add(achievement);
                    db.SaveChanges();
                    ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name");
                    return PartialView("_CreateForProject");
                }

                ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", achievement.ProjectId);
                return View(achievement);
            }
            catch (Exception)
            {
                return PartialView("_CreateForProject");
                //return RedirectToAction("CreateForProject");
            }

        }
        //------------------------------------------------
        // GET: Achievements/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Achievement achievement = db.Achievements.Find(id);
            if (achievement == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", achievement.ProjectId);
            return View(achievement);
        }

        // POST: Achievements/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Update,ProjectId")] Achievement achievement)
        {
            if (ModelState.IsValid)
            {
                db.Entry(achievement).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectId = new SelectList(db.Projects, "Id", "Name", achievement.ProjectId);
            return View(achievement);
        }

        // GET: Achievements/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Achievement achievement = db.Achievements.Find(id);
            if (achievement == null)
            {
                return HttpNotFound();
            }
            return View(achievement);
        }

        // POST: Achievements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Achievement achievement = db.Achievements.Find(id);
            db.Achievements.Remove(achievement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //------------------------------- Delete from Projects
        public ActionResult DeleteFromProjects(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Achievement achievement = db.Achievements.Find(id);
            if (achievement == null)
            {
                return HttpNotFound();
            }
            return View(achievement);
        }

        // POST: Achievements/DeleteFromProjects/5
        [HttpPost, ActionName("DeleteFromProjects")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteFromProjects(int id)
        {
            Achievement achievement = db.Achievements.Find(id);
            db.Achievements.Remove(achievement);
            db.SaveChanges();
            return RedirectToAction("Details", "Projects", new { id = achievement.ProjectId });
        }
        //------------------------------------

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectInfo/Controllers/AttachmentsController.cs
using ProjectInfo.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectInfo.Controllers
{
    [Authorize]
    public class AttachmentsController : Controller
    {
        // GET: Attachments
        public ActionResult Upload()
        {
            return PartialView("_Upload");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Upload(Attachment attachment)
        {
            try
            {
                if (attachment.File.ContentLength > 0)
                {
                    var whichProject = Url.RequestContext.RouteData.Values["id"];
                    var fileName = Path.GetFileName(attachment.File.FileName);
                    var pathDir = Path.Combine(Server.MapPath("~/Content/files"), (string)whichProject); ;
                    var pathFile = Path.Combine(pathDir, fileName);
                    
                    if (!Directory.Exists(pathDir)){
                        DirectoryInfo di = Directory.CreateDirectory(pathDir);
                    };
                    attachment.File.SaveAs(pathFile);

                }
            }
            catch (Exception)
            {
                //System.Windows.Forms.MessageBox.Show("No file attached");
            };



            //return Redirect(Request.UrlReferrer.ToString());

            // return RedirectToAction("Details", "Projects", new { id = Url.RequestContext.RouteData.Values["id"] });
            return PartialView("_Upload");
            //return view(Request.UrlReferrer.PathAndQuery);
        }
        [AllowAnonymous]
        public PartialViewResult Index(int id)
        {
            List<string> items = new List<string>();

            if (Directory.Exists(Server.MapPath("~/Content/files/" + id + "/"))){
                var dir = new DirectoryInfo(Server.MapPath("~/Content/files/" + id + "/"));
                FileInfo[] fileNames = dir.GetFiles("*.*");
                
                foreach (var file in fileNames)
                {
                    items.Add(file.Name);
                }
                return PartialView(items);
            }
            return PartialView(items);
        }
        [AllowAnonymous]
        public FileResult Download(string fileName, int? projectId)
        {
            return File(Server.MapPath("~/Content/files/") + projectId + "/" + fileName, System.Net.Mime.MediaTypeNames.Application.Octet);
        }

        public ActionResult Delete(string fileName, int projectId)
        {
            FileInfo file = new FileInfo(Server.MapPath("~/Content/files/") + projectId + "/" + fileName);
            file.Delete();
            DirectoryInfo dir = new DirectoryInfo((Server.MapPath("~/Content/files/") + projectId));
            FileInfo[] fileNames = dir.GetFiles("*.*");
            List<string> items = new List<string>();
            foreach (var item in fileNames)
            {
                items.Add(item.Name);
            }
            if (items.Count < 1 ){
                dir.Delete();
            }


            return RedirectToAction("Details", "Projects", new { id = projectId });

        }
    }
}

ProjectInfo/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjectInfo.Context;
using ProjectInfo.Models;
using System.IO;

namespace ProjectInfo.Controllers
{
    [Authorize]
    public class ProjectsController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        [AllowAnonymous]
        // GET: Projects
        public ActionResult Index()
        {
            var projects = db.Projects.Include(p => p.SelectedPM).Include(p => p.SelectedTeam);
            return View(projects.ToList());
        }

        [AllowAnonymous]
        // GET: Projects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // GET: Projects/Create
        public ActionResult Create()
        {
            ViewBag.ProjectManagerId = new SelectList(db.ProjectManagers, "Id", "Name");
            ViewBag.TeamId = new SelectList(db.Teams, "Id", "Name");
            return View();
        }

        // POST: Projects/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,TeamId,ProjectManagerId,StartDate,DeliveryDate,Status,Priority,Effort,DeliveryStatus,Overview,Risks")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Projects.Add(project);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProjectManagerId = new SelectList(db.ProjectManagers, "Id", "Name", project.ProjectManagerId);
            ViewBag.TeamId = new SelectList(db.Teams, "Id", "Name", project.TeamId);
            return View(project);
        }

        // GET: Projects/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProjectManagerId = new SelectList(db.ProjectManagers, "Id", "Name", project.ProjectManagerId);
            ViewBag.TeamId = new SelectList(db.Teams, "Id", "Name", project.TeamId);
            return View(project);
        }

        // POST: Projects/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,TeamId,ProjectManagerId,StartDate,DeliveryDate,Status,Priority,Effort,DeliveryStatus,Overview,Risks")] Project project)
        {
            if (ModelState.IsValid)
            {
                db.Entry(project).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProjectManagerId = new SelectList(db.ProjectManagers, "Id", "Name", project.ProjectManagerId);
            ViewBag.TeamId = new SelectList(db.Teams, "Id", "Name", project.TeamId);
            return View(project);
        }

        // GET: Projects/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Project project = db.Projects.Find(id);
            if (project == null)
            {
                return HttpNotFound();
            }
            return View(project);
        }

        // POST: Projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Project project = db.Projects.Find(id);
            db.Projects.Remove(project);
            db.SaveChanges();

            DirectoryInfo dir = new DirectoryInfo((Server.MapPath("~/Content/files/") + id));
            FileInfo[] files = dir.GetFiles("*.*");
            foreach (var item in files)
            {
                item.Delete();
            }
            dir.Delete();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjectInfo/Views/Projects/Create.cshtml
@model ProjectInfo.Models.Project

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Project</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TeamId, "TeamId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TeamId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeamId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProjectManagerId, "ProjectManagerId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ProjectManagerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProjectManagerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DeliveryDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DeliveryDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @*@Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })*@
                <select class="form-control" id="Status" name="Status">
                    <option>Not started</option>
                    <option>In progress</option>
                    <option>Cancelled</option>
                    <option>Completed</option>
                    <option>On hold</option>
                </select>
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Priority, new { htmlAttributes = new { @class = "form-control" } })*@
                <select class="form-control" id="Priority" name="Priority">
                    <option>High</option>
                    <option>Medium</option>
                    <option>Low</option>
                </select>
                @Html.ValidationMessageFor(model => model.Priority, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Effort, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.Effort, new { htmlAttributes = new { @class = "form-control" } })*@
                <select class="form-control" id="Effort" name="Effort">
                    <option>Big</option>
                    <option>Medium</option>
                    <option>Small</option>
                </select>
                @Html.ValidationMessageFor(model => model.Effort, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DeliveryStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.DeliveryStatus, new { htmlAttributes = new { @class = "form-control" } })*@
                <select class="form-control" id="DeliveryStatus" name="DeliveryStatus">
                    <option>Green</option>
                    <option>Amber</option>
                    <option>Red</option>
                </select>
                @Html.ValidationMessageFor(model => model.DeliveryStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Overview, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Overview, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Overview, "", new { @class = "text-danger" })
                </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Risks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Risks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Risks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjectInfo/Views/Projects/Delete.cshtml
@model ProjectInfo.Models.Project

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete @Html.DisplayFor(model => model.Name)?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SelectedPM.Name)
        </dt>

        <dd>
            <a href="mailto:@(Model.SelectedPM.Email)">@Html.DisplayFor(model => model.SelectedPM.Name)</a>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SelectedTeam.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SelectedTeam.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Effort)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Effort)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DeliveryStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeliveryStatus)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Overview)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Overview)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Risks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Risks)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ProjectInfo/Views/Projects/Details.cshtml
@model ProjectInfo.Models.Project

@{
    ViewBag.Title = "Details";
}


<div class="row">
    <div class="col-md-6">
        <h2>@Html.DisplayFor(model => model.Name)</h2>
        <div>
            <h3>Information</h3>
            <hr />
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.SelectedPM.Name)
                </dt>

                <dd>
                    <a href="mailto:@(Model.SelectedPM.Email)">@Html.DisplayFor(model => model.SelectedPM.Name)</a>
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.SelectedTeam.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.SelectedTeam.Name)
                </dd>


                <dt>
                    @Html.DisplayNameFor(model => model.StartDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.StartDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DeliveryDate)
                </dt>

                <dd id="delivery">
                    @Html.DisplayFor(model => model.DeliveryDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Status)
                </dt>

                <dd id="status">
                    @Html.DisplayFor(model => model.Status)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Priority)
                </dt>

                <dd id="priority">
                    @Html.DisplayFor(model => model.Priority)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Effort)
                </dt>

                <dd id="effort">
                    @Html.DisplayFor(model => model.Effort)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DeliveryStatus)
                </dt>

                <dd id="dstatus">
                    @Html.DisplayFor(model => model.DeliveryStatus)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Overview)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Overview)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Risks)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Risks)
                </dd>
            </dl>
        </div>
        <p>
            @if (User.Identity.IsAuthenticated == true)
            {
                @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) <span>|</span>
                                                                    }
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
    <div class="col-md-6">
        <h2><br></h2>
        @{Html.RenderAction("Index", "Attachments", new { projectId = Url.RequestContext.RouteData.Values["id"] });}
        <br />
        @if (User.Identity.IsAuthenticated == true)
        {
            { Html.RenderAction("Upload", "Attachments"); }
        }
    </div>
</div>
<div>
    @if (User.Identity.IsAuthenticated == true)
    {
        <button id="AddButton" class="btn btn-primary">Add new comment</button>
        <div id="AddComment" hidden="true">
            @{Html.RenderAction("CreateForProject", "Achievements");}
        </div>}
    @{Html.RenderAction("AchievementsOfProject", "Achievements", new { id = Model.Id });}

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


@*<script>


        $(document).ready(colorizeDetails)
    </script>*@